FROM nginx

COPY files/nginx.conf /etc/nginx/sites-available/default
COPY files/index.html /usr/share/nginx/html

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log
